### ISSUE TITLE
Add support for dweet.io

### ISSUE THREAD

**Issue by disquisitioner** [ericklein/air_quality#37]
Add support for [dweet.io](https://dweet.io), which provides a free cloud service for devices to publish messages and information,  This would make it easy to see the most recent sensor readings, information about the device itself (e.g., WiFi RSSI and IP address) and even error/status messages.    Uploads happen via an HTTP POST and JSON, which is easy to add given we already have HTTP connectivity support in the app.

**Comment by ericklein** [comment]
completed and in master
